### PR TITLE
Attach docstrings to constants and structures created by adt:defdata

### PR DESCRIPTION
**Pull request by rigettizach**

### CODE REVIEW

**Comment by fosskers** [comment]
This would be great to have. I just tried this library out today and was wondering if docstrings were available.

**Review by stylewarning — APPROVED** [review]

**Comment by stylewarning** [comment]
No idea how I missed this for 4 years.

**Comment by fosskers** [comment]
Thanks!

**Comment by fosskers** [comment]
Confirmed. The following CL:
```lisp
(adt:defdata colour
  "Docstring!"
  red
  green
  blue)
```
yields the following `describe` output:
```
COLOUR names the structure-class #<STRUCTURE-CLASS SCRIPTS::COLOUR>:
  Documentation:
    Docstring!
  Class precedence-list: COLOUR, ADT:ALGEBRAIC-DATA-TYPE,
                         STRUCTURE-OBJECT, SB-PCL::SLOT-OBJECT, T
  Direct superclasses: ADT:ALGEBRAIC-DATA-TYPE
  Direct subclasses: BLUE, GREEN, RED
  No slots.
```

**Pull request merged**
